modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/GirafiStudios/BetterTitleScreen/issues"
logoFile="logo.png"

[[mods]]
    modId="bettertitlescreen"
    version="${version}"
    side="CLIENT"
    displayName="Better Title Screen"
    displayURL="http://minecraft.curseforge.com/mc-mods/224223"
    authors="Girafi, Amadornes"
    description='''
    Better Title Screen is a client-side mod that provides options to customize Minecraft's title screen.
    '''