modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/GirafiStudios/BetterTitleScreen/issues"
logoFile="logo.png"
license="All Right Reserved"

[[mods]]
    modId="bettertitlescreen"
    version="${mod_version}"
    side="CLIENT"
    displayName="Better Title Screen"
    displayURL="http://minecraft.curseforge.com/mc-mods/224223"
    authors="Girafi"
    credits="Thanks to Amadornes for the original mod idea"
    description='''
    Better Title Screen is a client-side mod that provides options to customize Minecraft's title screen.
    '''

[[dependencies.waddles]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="AFTER"
    side="BOTH"